name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Worker Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        name: Install deps
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v3.0.0
        name: Sync commands to Discord 
        env:
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        with:
          cmd: sync
      - uses: borales/actions-yarn@v3.0.0
        name: Publish to Cloudflare
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        with:
          cmd: deploy
